name: Build JAR and Release MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build JAR with Maven
      run: mvn clean package -DskipTests

    - name: Set up JavaFX jmods
      run: |
        curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/22.0.1/openjfx-22.0.1_windows-x64_bin-jmods.zip
        unzip javafx.zip -d javafx-jmods

    - name: Copy JAR to root with desired name
      run: |
        mkdir dist
        copy target\*.jar dist\ShowSequencer-JavaFX.jar

    - name: Copy icon to dist
      run: copy src\icon.ico dist\icon.ico

    - name: Package MSI using jpackage
      run: |
        jpackage `
          -t msi `
          --name "ShowSequencer" `
          --input dist `
          --main-jar ShowSequencer-JavaFX.jar `
          --main-class com.example.showSequencerJavafx.ShowSequencer `
          --win-menu `
          --win-shortcut `
          --module-path javafx-jmods\javafx-jmods-22.0.1 `
          --add-modules javafx.controls,javafx.media,javafx.fxml `
          --icon dist\icon.ico `
          --dest dist

    - name: Zip project contents
      run: powershell Compress-Archive -Path dist\* -DestinationPath release-artifacts.zip

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist\*.msi
          dist\ShowSequencer-JavaFX.jar
          release-artifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
