name: Build and Package with jpackage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest  # Change to macos-latest or windows-latest if needed
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project
        run: |
           mvn package   

      - name: Run jpackage
        run: |
          jpackage -t msi --name "ShowSequencer" --input out/artifacts/ShowSequencer_JavaFX_jar/  --main-jar .\ShowSequencer-JavaFX.jar --main-class com.example.showSequencerJavafx.ShowSequencer --win-menu --win-shortcut --module-path "C:\Program Files\JavaFX\javafx-jmods-22.0.1" --add-modules javafx.controls,javafx.media,javafx.fxml --icon .\icon.ico

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app
          path: output/*
