name: Build and Package with jpackage

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: windows-latest  # Change to macos-latest or windows-latest if needed
    permissions: 
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JavaFX
        run: |
          Invoke-WebRequest -Uri "https://download2.gluonhq.com/openjfx/22.0.1/openjfx-22.0.1_windows-x64_bin-sdk.zip" -OutFile "javafx-sdk.zip"
          Expand-Archive -Path javafx-sdk.zip -DestinationPath .
          echo "JAVA_FX_PATH=$(pwd)\javafx-sdk-22.0.1\lib" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

      - name: Build the project
        run: |
          mvn package   

      - name: Run jpackage
        run: |
          jpackage -t msi --name "ShowSequencer" --input out\artifacts\ShowSequencer_JavaFX_jar\  --main-jar .\ShowSequencer-JavaFX.jar --main-class com.example.showSequencerJavafx.ShowSequencer --win-menu --win-shortcut --module-path "$env:JAVA_FX_PATH" --add-modules javafx.controls,javafx.media,javafx.fxml --icon src\icon.ico --dest output\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app
          path: output/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: output/*

